# Generated by Django 3.0.6 on 2020-06-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_autor_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
